---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes #can also remove the "update repository index" play. It's not necessary for package removal.

  - name: remove apache2 package
    apt:
      name: apache2
      state: absent

  - name: remove php support for apache
    apt:
      name: libapache2-mod-php
      state: absent
