---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache (Rocky)
    tags: always
    yum:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Rocky"

  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

##################### USERS #######################

- hosts: all
  become: true
  roles:
    - base

################## WORKSTATIONS #######################

- hosts: workstations
  become: true
  roles:
    - workstations

################### WEB SERVERS #######################

- hosts: web_servers
  become: true
  roles:
    - web_servers

######################### DB SERVERS ###########################

- hosts: db_servers
  become: true
  roles:
    - db_servers

########################## FILE SERVERS #########################

- hosts: file_servers
  become: true
  roles:
    - file_servers
