---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Rocky)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

################### WEB SERVERS #######################

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"



  - name: install apache and php for Rocky/CentOS servers
    tags: apache,rocky,httpd
    yum:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution in ["Rocky", "CentOS"]



  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

######################### DB SERVERS ###########################

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Rocky)
    tags: rocky,db,mariadb
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "Rocky"

  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

########################## FILE SERVERS #########################

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
