 - name: add ssh key for ansible
   authorized_key:
      user: ansible
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF1CEIOitpOaSSpjzrTc5VfOnAVlhVwNcJs6WnH0cB/+ ansible"

 - name: generate sshd_config file from template
   tags: ssh
   template:
     src: "{{ ssh_template_file }}"
     dest: /etc/ssh/sshd_config
     owner: root
     group: root
     mode: 0644
   notify: restart_sshd
